version: '3.4'

services:
  nutrifitback:
    image: nutrifitback
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8082:80
  mysql:
    image: mysql:8.0.30
    ports:
        - "3306:3306"
    expose:
      - '3306'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: