version: '3.4'

services:
  nutrifitback:
    image: nutrifitback
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 8082:80